lsi: false
safe: true
source: "./docs"
include:
  - "./_posts"
  - "./_layouts"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
show_dir_listing: true